# This CI Workflow was deployed and configured by WarpWing and Nate.
name: CI/CD (16.x)

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'

jobs:
  es-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm i

      - name: es-lint
        run: npm run eslint

  tests:
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm i

      - name: Run Tests
        env:
          HYPIXEL_KEY: ${{ secrets.HYPIXEL_KEY }}
        run: npm tests

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm i

      - name: Build
        run: npm run build --if-present

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm i

      - name: prettier
        run: npm run prettier:check
